### ISSUE TITLE
Unable to run junit test cases using chrome

### ISSUE THREAD

**Issue by prathimak** [serenity-bdd/serenity-jbehave#105]
Unable to run junit test cases using chrome, received below exception

java.lang.RuntimeException: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
xxxxx: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: xxxxxxxx
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:177)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories:

**Comment by wakaleo** [comment]
Are there any other exceptions? This stack simply indicates that the 802_CreateDisputes.story failed.

**Comment by prathimak** [comment]
Below is the complete log
Generating reports view to xxx' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 50 stories (of which 0 pending) containing 144 scenarios (of which 0 pending)
Failures in reports view: 144 scenarios failed
java.lang.RuntimeException: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
story: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: Stories
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:177)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
ry: org.jbehave.core.embedder.StoryManager$StoryExecutionFailed: 
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:553)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:238)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:216)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:175)
	... 6 more

**Comment by wakaleo** [comment]
This doesn't look like a Serenity issue from the stack trace. What versions are you using? Is your chromedriver executable up to date?

**Comment by prathimak** [comment]
thank you for your help looks like some merge issue its resolved now
