### ISSUE TITLE
EmptyStackException

### ISSUE THREAD

**Issue by beetlezhuk** [serenity-bdd/serenity-jbehave#111]
I have a jbehave story, which includes GivenStories abc.story. That abc.story also includes GivenStories xyz .story. So as a result I'm calling 2 stories before doing actual stuff.

The tests are running well and passing, however I'm getting this error:

java.util.EmptyStackException
at java.util.Stack.peek(Stack.java:102)
at java.util.Stack.pop(Stack.java:84)
at net.serenitybdd.jbehave.SerenityReporter.afterScenario(SerenityReporter.java:543)
at org.jbehave.core.reporters.DelegatingStoryReporter.afterScenario(DelegatingStoryReporter.java:43)
at org.jbehave.core.reporters.ConcurrentStoryReporter.afterScenario(ConcurrentStoryReporter.java:175)
at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:347)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Also, the index.html file is not getting created in reports.
Serenity version 1.1.42

Does anyone know what's the problem here?

**Comment by richard-melvin** [comment]
I saw this too, when GivenStories for a scenario referenced a story with a GivenStories  clause.

**Comment by wakaleo** [comment]
Try with Serenity 1.2.2 and serenity-jbehave 1.21.0

**Comment by wakaleo** [comment]
Closed for lack of activity.
