### ISSUE TITLE
Getting ReportGenerationFailedError - HTML report is broken

### ISSUE THREAD

**Issue by baskarank** [serenity-bdd/serenity-jbehave#118]
Hi Team,
[Serenity Reports.pdf](https://github.com/serenity-bdd/serenity-jbehave/files/854960/Serenity.Reports.pdf)

I am using the following versions and getting the errors given below.

  <serenity.version>1.2.2-rc.1</serenity.version>
        <serenity.jbehave.version>1.18.0</serenity.jbehave.version>

I tried with latest versions in mvn repository as well, still getting the issue. Tests executed and display results in plain text in html and not displaying the tables and screenshots.

**Errors:**

java.lang.RuntimeException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:182)
java.lang.RuntimeException: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate configuration report
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:182)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:163)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:112)
	at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:520)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:505)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:122)
	at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:435)
	at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:174)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@34bde49d
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:223)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:35)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.thucydides.core.resources.ResourceCopyingError: Couldn't close the zip file C:\Users\Administrator\.m2\repository\org\codehaus\groovy\groovy-all\2.4.4\groovy-all-2.4.4.jar
	at net.thucydides.core.resources.ResourceList.getResourcesFromJarFile(ResourceList.java:151)
	at net.thucydides.core.resources.ResourceList.getResources(ResourceList.java:89)
	at net.thucydides.core.resources.ResourceList.systemPropertiesClasspathElements(ResourceList.java:79)
	at net.thucydides.core.resources.ResourceList.list(ResourceList.java:51)
	at net.thucydides.core.reports.html.HtmlResourceCopier.to(HtmlResourceCopier.java:41)
	at net.thucydides.core.reports.html.HtmlReporter.copyResourcesToOutputDirectory(HtmlReporter.java:80)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:221)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:35)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at net.thucydides.core.resources.ResourceList.loadZipFileWithMaxRetries(ResourceList.java:117)
	at net.thucydides.core.resources.ResourceList.loadZipFileWithMaxRetries(ResourceList.java:127)
	at net.thucydides.core.resources.ResourceList.loadZipFileWithMaxRetries(ResourceList.java:127)
	at net.thucydides.core.resources.ResourceList.loadZipFileWithMaxRetries(ResourceList.java:127)
	at net.thucydides.core.resources.ResourceList.zipFileFor(ResourceList.java:112)
	at net.thucydides.core.resources.ResourceList.getResourcesFromJarFile(ResourceList.java:135)
	at net.thucydides.core.resources.ResourceList.getResources(ResourceList.java:89)
	at net.thucydides.core.resources.ResourceList.systemPropertiesClasspathElements(ResourceList.java:79)
	at net.thucydides.core.resources.ResourceList.list(ResourceList.java:51)
	at net.thucydides.core.reports.html.HtmlResourceCopier.to(HtmlResourceCopier.java:41)
	at net.thucydides.core.reports.html.HtmlReporter.copyResourcesToOutputDirectory(HtmlReporter.java:80)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:221)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:35)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Results :

Tests in error: 
  JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 » Runtime

**Comment by wakaleo** [comment]
Could you try a more recent version?

**Comment by baskarank** [comment]
Tried with the given latest version and getting new errors as given below.

**version:**

<serenity.version>1.2.2-rc.1</serenity.version>
<serenity.jbehave.version>1.18.0</serenity.jbehave.version>

Errors:

INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Sample Serenity project using JBehave and WebDriver 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ serenitydemo ---
[INFO] Deleting C:\Baskaran\BDD Testing\DemoFor-SerenityJBehave-master\DemoFor-SerenityJBehave-master\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ serenitydemo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Baskaran\BDD Testing\DemoFor-SerenityJBehave-master\DemoFor-SerenityJBehave-master\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ serenitydemo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ serenitydemo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ serenitydemo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to C:\Baskaran\BDD Testing\DemoFor-SerenityJBehave-master\DemoFor-SerenityJBehave-master\target\test-classes
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\groovy\groovy-all\2.4.4\groovy-all-2.4.4.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\jbehave\jbehave-core\4.1\jbehave-core-4.1.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.22\plexus-utils-3.0.22.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.22\plexus-utils-3.0.22.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; invalid END header (bad central directory offset)
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ serenitydemo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ serenitydemo ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Baskaran\BDD Testing\DemoFor-SerenityJBehave-master\DemoFor-SerenityJBehave-master\target\serenitydemo-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ serenitydemo ---
[INFO] Downloading: http://jcenter.bintray.com/org/apache/maven/surefire/surefire-junit4/2.19.1/surefire-junit4-2.19.1.pom
[INFO] Downloaded: http://jcenter.bintray.com/org/apache/maven/surefire/surefire-junit4/2.19.1/surefire-junit4-2.19.1.pom (4 KB at 8.5 KB/sec)
[INFO] Downloading: http://jcenter.bintray.com/org/apache/maven/surefire/surefire-junit4/2.19.1/surefire-junit4-2.19.1.jar
[INFO] Downloaded: http://jcenter.bintray.com/org/apache/maven/surefire/surefire-junit4/2.19.1/surefire-junit4-2.19.1.jar (74 KB at 362.8 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.112 s
[INFO] Finished at: 2017-03-21T05:20:53+00:00
[INFO] Final Memory: 32M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project serenitydemo: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/jbehave/core/junit/JUnitStories

**Comment by baskarank** [comment]
Hi Team,
Could you please provide your support on this, thank you in advance.

**Comment by baskarank** [comment]
Thank you wakaleo for your clarification on this, i am able to get the report for the same project with same setup in Windows 7 and Windows 10. But, I am still facing issue with the Windows server 2012 R2.

**Comment by baskarank** [comment]
@wakaleo  Could you please share your thoughts on the failure of test execution in Windows server 2012 R2 where as the same test and same versions of the software cause test execution as passed, generating reports perfectly in windows 10 and windows 7.

Below are the errors which i received during failure in WS 2012.

INFO] Compiling 7 source files to C:\Baskaran\BDD Testing\syrup_automation\target\test-classes
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\groovy\groovy-all\2.4.4\groovy-all-2.4.4.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\jbehave\jbehave-core\4.1\jbehave-core-4.1.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.22\plexus-utils-3.0.22.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Administrator\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.22\plexus-utils-3.0.22.jar; invalid END header (bad central directory offset)
[ERROR] error reading C:\Users\Administrator\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; invalid END header (bad central directory offset)
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ syrup_automation ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ syrup_automation ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Baskaran\BDD Testing\syrup_automation\target\syrup_automation-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ syrup_automation ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.379 s
[INFO] Finished at: 2017-03-23T13:13:52+00:00
[INFO] Final Memory: 31M/252M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project syrup_automation: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/jbehave/core/junit/JUnitStories
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:96)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:311)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:191)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:134)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.jbehave.core.junit.JUnitStories
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 32 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by wakaleo** [comment]
It could well be a corrupted Maven repository:

**C:\Users\Administrator.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar; invalid END header (bad central directory offset)**

Try deleting C:\Users\Administrator.m2

**Comment by baskarank** [comment]
Thanks a lot @wakaleo for your support , i was able to fix it and reports are generating properly after purging local maven repository with cmd - **mvn dependency:purge-local-repository**

**Comment by masoumiaa** [comment]
I had the same issue and running **mvn dependency:purge-local-repository** solved the problem.
Thanks @baskarank :)
