### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException while parsing param

### ISSUE THREAD

**Issue by venkatesgopi** [serenity-bdd/serenity-jbehave#127]
Sample story with meta data:

Scenario: 1. xxxxxxxxxxxxxxxxxxx
Meta: @requestTemplate requests/Cxxxxxxxxxxxxxxxxxxxxxxxxxxxx
@header {"SOAPAction": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}

Version: 1.4.1-rc.7
serenity-jbehave: 1.26.0-rc.3

java.lang.ArrayIndexOutOfBoundsException: 27339
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:451)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:431)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:492)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:337)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:100)
	at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:75)
	at org.jbehave.core.steps.StepCreator.paranamerParameterNames(StepCreator.java:198)
	at org.jbehave.core.steps.StepCreator.parameterNames(StepCreator.java:135)
	at org.jbehave.core.steps.StepCreator.access$900(StepCreator.java:37)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:640)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:317)

**Comment by wakaleo** [comment]
The stack trace seems to indicate a JBehave issue, rather than a Serenity one.

**Comment by wakaleo** [comment]
Closing due to lack of activity
