### ISSUE TITLE
Some steps throw exception: java.lang.IndexOutOfBoundsException: No group 1

### ISSUE THREAD

**Issue by lega-land** [serenity-bdd/serenity-jbehave#142]
Hello!

I'm trying to upgrade from serenity-jbehave 1.1.0 to latest 1.33.0.
Receiving strange error during test run:
```
java.lang.IndexOutOfBoundsException: No group 1
	at java.util.regex.Matcher.group(Matcher.java:538)
	at org.jbehave.core.steps.StepCreator.delimitedNameFor(StepCreator.java:498)
	at org.jbehave.core.steps.StepCreator.parameterForPosition(StepCreator.java:424)
	at org.jbehave.core.steps.StepCreator.parameterValuesForStep(StepCreator.java:394)
	at org.jbehave.core.steps.StepCreator.access$1200(StepCreator.java:44)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:781)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:730)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1090)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:955)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:994)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:904)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
Step:
`
And the user set local option 'UserSettings(10003).OnStartup' eq '1'
`

Step Definition:
```
@Given("the user set local option '$key' eq '$value'")
public void theUserSetLocalOptionValue(String key, String value) {
}
```

I receive same exception in steps that contain int parameter, e.g. '0', '1'.

Any idea what it might be?

**Comment by wakaleo** [comment]
Not really; from the stack trace it looks like a JBehave issue of some kind.

**Comment by lega-land** [comment]
Found reason in our CustomSerenityStories.
```
    @Override
    public Configuration configuration() {
        Configuration configuration = super.configuration();
        // Allow meta filters to ignore stories listed in GivenStories
        configuration.storyControls().doIgnoreMetaFiltersIfGivenStory(true);
        configuration.storyReporterBuilder().withReporters(new CustomStoryReporter());
        configuration.useParameterControls(new ParameterControls().useNameDelimiterLeft("[").useNameDelimiterRight("]"));
        return configuration;
    }
```
This changed delimitedNamePattern in org.jbehave.core.steps.StepCreator from `<(\w+?)>` to `[(\w+?)]`.

**Comment by wakaleo** [comment]
Thanks for the update.
