### ISSUE TITLE
Failed to generate reports - Failed to process FreeMarker template

### ISSUE THREAD

**Issue by Shafic777** [serenity-bdd/serenity-jbehave#167]
Facing problem in report generation,

Execution Log:
et.serenitybdd.core.exceptions.SerenityManagedException: Failed to generate configuration report
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at net.thucydides.core.reports.ReportService.waitForReportGenerationToFinish(ReportService.java:216)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:192)
        at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
        at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:504)
        at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:489)
        at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:51)
        at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:127)
        at org.jbehave.core.embedder.PerformableTree.performBeforeOrAfterStories(PerformableTree.java:441)
        at org.jbehave.core.embedder.StoryManager.performStories(StoryManager.java:130)
        at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:107)
        at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:86)
        at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
        at net.serenitybdd.jbehave.embedders.ExtendedEmbedder.runStoriesAsPaths(ExtendedEmbedder.java:60)
        at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:203)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
Caused by: net.thucydides.core.reports.ReportGenerationFailedError: Failed to generate reports using net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@21694e53
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:257)
        at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32)
        at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to merge template: Failed to process FreeMarker template
        at net.thucydides.core.reports.html.Merger$MergeBuilder.to(Merger.java:39)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportPage(HtmlAcceptanceTestReporter.java:141)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:127)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:255)
        at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32)
        at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: net.thucydides.core.reports.templates.TemplateMergeException: Failed to process FreeMarker template

Pom.xml
--------

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.serenitybdd.showcase</groupId>
    <artifactId>serenity-jbehave-showcase</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Serenity JBehave project</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.21</serenity.version>
        <serenity.maven.version>1.11.0</serenity.maven.version>
        <serenity.jbehave.version>1.35.0</serenity.jbehave.version>

    </properties>
  <dependencies>

         <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>RELEASE</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
             <exclusions>
                 <exclusion>
                     <groupId>commons-collections</groupId>
                     <artifactId>commons-collections</artifactId>
                 </exclusion>
              </exclusions>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-jbehave</artifactId>
            <version>${serenity.jbehave.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>net.serenity-bdd</groupId>
                    <artifactId>serenity-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.1</version>
        </dependency>

        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>1.6.3</version>
        </dependency>
      <dependency>
          <groupId>org.hamcrest</groupId>
          <artifactId>hamcrest-junit</artifactId>
          <version>2.0.0.0</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.hamcrest</groupId>
          <artifactId>hamcrest-core</artifactId>
          <version>1.3</version>
          <scope>test</scope>
      </dependency>
  <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.9.0</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

  <build>
        <plugins>

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/com/wap/test/*.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.4</version>
                <configuration>
                    <failFast>false</failFast>
                    <rules>
                        <DependencyConvergence></DependencyConvergence>
                        <requireReleaseDeps>
                            <onlyWhenRelease>false</onlyWhenRelease>
                        </requireReleaseDeps>
                        <requireJavaVersion>
                            <version>${java.version}</version>
                        </requireJavaVersion>
                    </rules>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>1.6.3</version>
                 <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by wakaleo** [comment]
Could you try using the same serenity-maven-plugin and serenity-core versions (e.g. 1.8.21)?

**Comment by Shafic777** [comment]
It worked with same versions .Thanks

**Comment by Shafic777** [comment]
Hi John,

This issue seems to occurring for scenario's with inline table parameters only ..
Ex: Story file
Scenario: Register  rejected correction of Application
Meta:
@destructApp
Given Application details to be created
|ApplicationStatus|AllocationStatus|ApplicationType|ApprovalStatus|
|0                |1               |NEW            |SUBMITTED     |
Then call create costposting api's to generate costID

Step Definition:
-------------
@Given("Application details to be created $examplesTable")
    public void givenApplicationDetailsToBeCreated(ExamplesTable parameterTable) {

        String applicationType=null;
        String approvalStatus=null;
        String allocationStatus=null;
        String applicationStatus=null;
        for (Map<String,String> row : parameterTable.getRows()) {

             applicationType = row.get("ApplicationType");
             allocationStatus = row.get("AllocationStatus");
             applicationStatus = row.get("ApplicationStatus");
             approvalStatus = row.get("ApprovalStatus");
        }

**Comment by wakaleo** [comment]
Can you provide a sample project?
