### ISSUE TITLE
Building master branch locally for a baseline but 5 tests fail.

### ISSUE THREAD

**Issue by mithuns** [serenity-bdd/serenity-jbehave#169]
Hi, 

I just checked out the master branch and did 
`gradle build`

And 5 tests fail for some reason. 
These are the tests:- 

```
net.serenitybdd.jbehave.WhenRunningWebJBehaveStoriesUsingAdvancedBrowserManagement > should_be_able_to_specify_the_browser_in_the_base_test FAILED
    java.lang.AssertionError:
    Expected: is <SUCCESS>
         but: was <ERROR>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningWebJBehaveStoriesUsingAdvancedBrowserManagement.should_be_able_to_specify_the_browser_in_the_base_test(WhenRunningWebJBehaveStoriesUsingAdvancedBrowserManagement.java:61)

net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots > web_tests_should_take_screenshots FAILED
    java.lang.AssertionError:
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots.web_tests_should_take_screenshots(WhenRunningJBehaveStoriesWithScreenshots.java:34)

net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots > web_tests_should_take_screenshots_with_multiple_scenarios FAILED
    java.lang.AssertionError:
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots.web_tests_should_take_screenshots_with_multiple_scenarios(WhenRunningJBehaveStoriesWithScreenshots.java:49)

net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots > web_tests_should_take_screenshots_with_nested_step_libraries FAILED
    java.lang.AssertionError:
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots.web_tests_should_take_screenshots_with_nested_step_libraries(WhenRunningJBehaveStoriesWithScreenshots.java:82)

net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots > web_tests_should_take_screenshots_for_multiple_tests FAILED
    java.lang.AssertionError:
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStoriesWithScreenshots.web_tests_should_take_screenshots_for_multiple_tests(WhenRunningJBehaveStoriesWithScreenshots.java:64)

262 tests completed, 5 failed, 4 skipped
:test FAILED

FAILURE: Build failed with an exception.

```

Am I missing something ? 

OS: Windows 10 64 bit 
Gradle: 4.5.1
JAVA:- 1.8.0_151

**Comment by wakaleo** [comment]
It might be an OS-specific thing, as I'm not seeing this failure locally or on the build server. I will take a look at the tests.

**Comment by mithuns** [comment]
I think we can close this, if I come across this again I will open a new issue. 
This reminds me , I guess you are not using a [Probot-Stale](https://probot.github.io/apps/stale/) that auto-closes stale issues.
I would humbly recommend that.
