### ISSUE TITLE
java.lang.StackOverflowError error

### ISSUE THREAD

**Issue by murthysp** [serenity-bdd/serenity-jbehave#188]
java.lang.StackOverflowError
	at com.sun.proxy.$Proxy27.how(Unknown Source)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.assertValidFindBy(SmartAnnotations.java:479)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.buildByFromFindBy(SmartAnnotations.java:271)
	at net.serenitybdd.core.annotations.locators.SmartAnnotations.buildBy(SmartAnnotations.java:231)
	at net.thucydides.core.annotations.locators.SmartElementLocator.<init>(SmartElementLocator.java:25)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:61)
	at net.thucydides.core.annotations.locators.SmartAjaxElementLocator.<init>(SmartAjaxElementLocator.java:51)
	at net.thucydides.core.annotations.locators.SmartElementLocatorFactory.createLocator(SmartElementLocatorFactory.java:23)
	at net.thucydides.core.annotations.locators.SmartFieldDecorator.decorate(SmartFieldDecorator.java:48)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)

**Comment by murthysp** [comment]
at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:55)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)
	at net.thucydides.core.steps.PageObjectDependencyInjector.injectDependenciesInto(PageObjectDependencyInjector.java:33)
	at net.thucydides.core.steps.PageObjectDependencyInjector.instantiatePageObjectIfNotAssigned(PageObjectDependencyInjector.java:56)

**Comment by murthysp** [comment]
https://github.com/jinnujani/sampleProject here is the sample project and serenity version is 1.5.3

**Comment by wakaleo** [comment]
This build needs proprietary dependencies so does not run locally. The versions are also very old. Try updating all the versions.

**Comment by murthysp** [comment]
Even with the latest versions i am getting the same error.
<serenity.version>1.9.4</serenity.version>
		<serenity.jbehave.version>1.38.0</serenity.jbehave.version>
		<serenity.maven.version>1.1.37-rc.6</serenity.maven.version>

**Comment by wakaleo** [comment]
1.1.37 is not a recent version

**Comment by murthysp** [comment]
I just want to add few comments on behavior.  If the when statement is the last step in the story file it is running fine. If I add any other step after that when statement I am getting the mentioned error. hope this may give some inputs to troubleshoot.

**Comment by wakaleo** [comment]
Can you produce a sample project to reproduce the issue?

**Comment by murthysp** [comment]
@wakaleo you just need class file or project  application has ip restrictions will not run from new ip

**Comment by wakaleo** [comment]
It needs to be a full working project that can run anywhere and that reproduces the issues. But first, update all of your dependencies

**Comment by murthysp** [comment]
I have updated all the dependencies as follows and still having the same issue. can you please confirm my dependencies are good?

<serenity.version>1.9.4</serenity.version>
		<serenity.jbehave.version>1.38.0</serenity.jbehave.version>
		<serenity.maven.version>1.9.4</serenity.maven.version>
        <serenity.rest.verion>1.2.4</serenity.rest.verion>
		<log4j.version>2.8.1</log4j.version>
		<ojdbc6.version>11.2.0.3</ojdbc6.version>
		<sqljdbc.version>1.0.2</sqljdbc.version>
		<ws.portal.version>1.0</ws.portal.version>
        <json.webtoken.version>0.2</json.webtoken.version>
        <slf4j.version>1.7.7</slf4j.version>
        <cxf.version>3.1.12</cxf.version>
        <slf4j-log4j12.version>1.5.8</slf4j-log4j12.version>

**Comment by murthysp** [comment]
@wakaleo Thanks you so much for your inputs the issue was caused by a recursive call in one of the methods.
