### ISSUE TITLE
Build fail with serenity-core v1.1.25-rc.4

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-jbehave#35]
It seems that jbehave should be updated to work with 1.1.25-rc.4. 

net.serenitybdd.jbehave.WhenRunningJBehaveStories > should_be_able_to_declare_a_story_as_wip_using_a_tag                                                                           FAILED
    java.lang.AssertionError: 
    Expected: is <SKIPPED>
         but: was <SUCCESS>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStories.should_be_able_to_declare_a_story_as_wip_using_a_tag(WhenRunningJBehaveStories.java:501)

net.serenitybdd.jbehave.WhenRunningJBehaveStories > should_be_able_to_declare_a_scenario_as_pending_or_skipped_using_a_tag                                                         FAILED
    java.lang.AssertionError: 
    Expected: is <SKIPPED>
         but: was <SUCCESS>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStories.should_be_able_to_declare_a_scenario_as_pending_or_skipped_using_a_tag(WhenRunningJBehaveStories.java:519)

net.serenitybdd.jbehave.WhenRunningJBehaveStories > a_tagged_skipped_outcome_should_have_skipped_steps                                                                             FAILED
    java.lang.AssertionError: 
    Expected: is <SKIPPED>
         but: was <SUCCESS>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStories.a_tagged_skipped_outcome_should_have_skipped_steps(WhenRunningJBehaveStories.java:560)

net.serenitybdd.jbehave.WhenRunningJBehaveStories > skipped_stories_should_not_be_executed                                                                                         FAILED
    java.lang.AssertionError: 
    Expected: is <SKIPPED>
         but: was <SUCCESS>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStories.skipped_stories_should_not_be_executed(WhenRunningJBehaveStories.java:631)

net.serenitybdd.jbehave.WhenRunningJBehaveStories > wip_or_skipped_stories_should_not_be_executed                                                                                  FAILED
    java.lang.AssertionError: 
    Expected: is <SKIPPED>
         but: was <SUCCESS>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at net.serenitybdd.jbehave.WhenRunningJBehaveStories.wip_or_skipped_stories_should_not_be_executed(WhenRunningJBehaveStories.java:647)

**Comment by YamStranger** [comment]
Fixed
