### ISSUE TITLE
IE unable to launch (The path to the driver executable must be set by the webdriver.ie.driver system property)

### ISSUE THREAD

**Issue by selvavaithi** [serenity-bdd/serenity-jbehave#60]
Hi Serenity team,
When trying to run serenity script in IE im facing with the following error. In my "serenity.properties" file have added webdriver.ie.driver = src/test/resource/IEDriverServer.exe
webdriver.driver = iexplorer but still getting the following error. While trying to run in normal selenium Code the IE works fine. Can you guys help me on it.
Im using 
Eclispe - Version: Mars.2 Release (4.5.2)
Serenity - 1.1.28

Console: 

[pool-1-thread-1] ERROR net.serenitybdd.core.Serenity - Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.getTitle(WebDriverFacade.java:210)
	at com.serentiy.PCHserenity.pageobject.RegisterPCHpageObject.verifyRegisterpage(RegisterPCHpageObject.java:67)
	at com.serentiy.PCHserenity.model.RegisterPCHpages.verifyPageIsRegistration(RegisterPCHpages.java:28)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.CGLIB$verifyPageIsRegistration$0(<generated>)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168$$FastClassByCGLIB$$768575fe.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.verifyPageIsRegistration(<generated>)
	at com.serentiy.PCHserenity.steps.RegisterPCHSteps.thenIShouldPresentInRegistrationPage(RegisterPCHSteps.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
...

Failed to run story stories/register_pch.story
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:175)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:170)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at com.serentiy.PCHserenity.model.RegisterPCHpages.openPCHurl(RegisterPCHpages.java:18)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.CGLIB$openPCHurl$4(<generated>)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168$$FastClassByCGLIB$$768575fe.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
	at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.openPCHurl(<generated>)
	at com.serentiy.PCHserenity.steps.RegisterPCHSteps.givenIGoToPCHWebsite(RegisterPCHSteps.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:546)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:510)
	at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:476)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:336)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:201)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
	... 36 more
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
	at org.openqa.selenium.ie.InternetExplorerDriverService.access$000(InternetExplorerDriverService.java:32)
	at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:167)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:251)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:172)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:150)
	at net.thucydides.core.webdriver.WebdriverInstanceFactory.newInternetExplorerDriver(WebdriverInstanceFactory.java:91)
	at net.thucydides.core.webdriver.WebDriverFactory.internetExplorerDriver(WebDriverFactory.java:552)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:187)
	... 37 more

**Comment by YamStranger** [comment]
Hello @selvavaithi 
Property webdriver.driver is should be described in serenity.properties: 
>    What browser do you want your tests to run in, for example firefox, chrome, phantomjs or iexplorer. You can also use the driver property as a shortcut.

Property webdriver.ie.driver it is selenium property so easiest way to provide it - using -D option of your test, for example (and it should not be provided in serenity.properties)

java -jar some.jar -Dwebdriver.ie.driver=src/test/resource/IEDriverServer.exe 

OR 
you can add src/test/resource/IEDriverServer.exe  in your class path using PATH environment

**Comment by selvavaithi** [comment]
Thanks @YamStranger
