### ISSUE TITLE
Report generation failure:  java.lang.RuntimeException 

### ISSUE THREAD

**Issue by selvavaithi** [serenity-bdd/serenity-jbehave#61]
Hi Team,
I'm using Serenity + JBehave + webdriver. When every executing the code the test is successfully executed but the report is not being generated. While report generation getting the following error. Can you help me on this ? Thanks in advance.

Generating reports view to 'D:\WorkSpace\PCHwebtest\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 1 stories (of which 0 pending) containing 2 scenarios (of which 0 pending)
java.lang.RuntimeException: java.lang.RuntimeException: Report generation failure
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:161)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.RuntimeException: Report generation failure
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:166)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:153)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:103)
	at net.serenitybdd.jbehave.SerenityReporter.generateReports(SerenityReporter.java:480)
	at net.serenitybdd.jbehave.SerenityReporter.afterStory(SerenityReporter.java:458)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:121)
	at org.jbehave.core.embedder.StoryRunner.runBeforeOrAfterStories(StoryRunner.java:86)
	at org.jbehave.core.embedder.StoryManager.runBeforeOrAfterStories(StoryManager.java:96)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:91)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:203)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.run(SerenityReportingRunner.java:159)
	... 6 more
Caused by: java.nio.file.FileSystemException: target\site\serenity\SERENITY-JUNIT-96236cd9b817521193cb5fda27d2cec16af60a21ac71e7486be5121f09e93559.xml976efa65-478a-41a8-81f6-6405eadf90ec -> target\site\serenity\SERENITY-JUNIT-96236cd9b817521193cb5fda27d2cec16af60a21ac71e7486be5121f09e93559.xml: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:59)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:164)
	... 17 more

**Comment by wakaleo** [comment]
What version of serenity-core are you using?

**Comment by YamStranger** [comment]
Hello @selvavaithi 

Please try to use serenity core v1.1.29-rc.1 and serenity-jbehave v1.8.0. 
This but should be fixed latest release. 

Thanks!

**Comment by selvavaithi** [comment]
Hi @wakaleo i have used serenity core v1.1.28 and serenity-jbehave v1.6.0. Now when changing the version as per @YamStranger the issue solved. 

Thanks @wakaleo and @YamStranger
