### ISSUE TITLE
IE unable to launch (net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver)

### ISSUE THREAD

**Issue by Kuppusamyi** [serenity-bdd/serenity-jbehave#76]
Hi Serenity team,

When trying to run serenity script in IE im facing with the following error. In my "serenity.properties" file have added webdriver.ie.driver=C:\\Automation\\Resources\\IEDriverServer.exe
-Dwebdriver.driver = iexplorer but still getting the following error. While trying to run in normal selenium Code the IE works fine. Can you guys help me on it.
I'm using

Eclispe : Luna
Serenity - 1.1.28

Console:

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
        at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:141)
        at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:128)
        at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:100)
        at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:334)
        at com.dnb.automation.trade.pages.DSCUILoginPage.getURLAndLaunchApplication(DSCUILoginPage.java:31)
        at com.dnb.automation.trade.tests.DSCUILoginPageTest.lanuchApplication(DSCUILoginPageTest.java:18)
        at com.dnb.automation.trade.tests.DSCUILoginPageTest$$EnhancerByCGLIB$$916b8e01.CGLIB$lanuchApplication$0(<generated>)
        at com.dnb.automation.trade.tests.DSCUILoginPageTest$$EnhancerByCGLIB$$916b8e01$$FastClassByCGLIB$$ba726aab.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:329)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:314)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:291)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
        at com.dnb.automation.trade.tests.DSCUILoginPageTest$$EnhancerByCGLIB$$916b8e01.lanuchApplication(<generated>)
        at com.dnb.automation.trade.steps.DSCUILoginPageSteps.getURL(DSCUILoginPageSteps.java:23)
        (reflection-invoke)
        at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
        at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
at net.thucydides.core.webdriver.WebDriverFacade.getTitle(WebDriverFacade.java:210)
at com.serentiy.PCHserenity.pageobject.RegisterPCHpageObject.verifyRegisterpage(RegisterPCHpageObject.java:67)
at com.serentiy.PCHserenity.model.RegisterPCHpages.verifyPageIsRegistration(RegisterPCHpages.java:28)
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.CGLIB$verifyPageIsRegistration$0()
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168$$FastClassByCGLIB$$768575fe.invoke()
at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)
at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)
at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)
at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.verifyPageIsRegistration()
at com.serentiy.PCHserenity.steps.RegisterPCHSteps.thenIShouldPresentInRegistrationPage(RegisterPCHSteps.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
...

Failed to run story stories/register_pch.story
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:130)
at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:102)
at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:175)
at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:170)
at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
at com.serentiy.PCHserenity.model.RegisterPCHpages.openPCHurl(RegisterPCHpages.java:18)
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.CGLIB$openPCHurl$4()
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168$$FastClassByCGLIB$$768575fe.invoke()
at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:348)
at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:333)
at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:308)
at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:130)
at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:57)
at com.serentiy.PCHserenity.model.RegisterPCHpages$$EnhancerByCGLIB$$2e9bf168.openPCHurl()
at com.serentiy.PCHserenity.steps.RegisterPCHSteps.givenIGoToPCHWebsite(RegisterPCHSteps.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:595)
at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:566)
at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:546)
at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:510)
at org.jbehave.core.embedder.StoryRunner.runStepsWithLifecycle(StoryRunner.java:476)
at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:336)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.ie.InternetExplorerDriver
at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:201)
at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:139)
... 36 more
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
at org.openqa.selenium.ie.InternetExplorerDriverService.access$000(InternetExplorerDriverService.java:32)
at org.openqa.selenium.ie.InternetExplorerDriverService$Builder.findDefaultExecutable(InternetExplorerDriverService.java:167)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
at org.openqa.selenium.ie.InternetExplorerDriver.setupService(InternetExplorerDriver.java:251)
at org.openqa.selenium.ie.InternetExplorerDriver.(InternetExplorerDriver.java:172)
at org.openqa.selenium.ie.InternetExplorerDriver.(InternetExplorerDriver.java:150)
at net.thucydides.core.webdriver.WebdriverInstanceFactory.newInternetExplorerDriver(WebdriverInstanceFactory.java:91)
at net.thucydides.core.webdriver.WebDriverFactory.internetExplorerDriver(WebDriverFactory.java:552)
at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:187)
... 37 more

**Comment by YamStranger** [comment]
Hello @Kuppusamyi 
Please try to run your tests with command line option:  -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe

webdriver.ie.driver it is not serenity property, it should be passed to selenium. 
And webdriver.driver you can add to serenty properties - it can be read from property file

**Comment by Kuppusamyi** [comment]
Hi YamStranger,

mvn test verify -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe

If I run this command through Command line, the default browser (Firefox) will be running.

For any concerns and clarifications let us know.

**Comment by Kuppusamyi** [comment]
Hi team,

mvn test verify -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe

If I run this command through Command line, the default browser (Firefox) will be running.
For any concerns and clarifications let us know.


Thanks & Regards
Iyyappan K.

**Comment by wakaleo** [comment]
Hi Iyyappan,

Where do you have your serenity.properties file in your directory structure?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 25 April 2016 at 11:42:25 AM, Kuppusamyi (notifications@github.com) wrote:

Hi team,

mvn test verify -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe

If I run this command through Command line, the default browser (Firefox) will be running.
For any concerns and clarifications let us know.


Thanks & Regards
Iyyappan K.

**Comment by Kuppusamyi** [comment]
Hi Team,

I’m using Maven Project. The Folder Structure Looks Like

Project Name
src/main/java
src/test/java
src/test/resouces
   serenity.properties
pom.xml


Thanks & Regards
Iyyappan K.

**Comment by YamStranger** [comment]
Hello @Kuppusamyi 

Your first message:  
>When trying to run serenity script in IE im facing with the following error. In my "serenity.properties" file have added webdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe
-Dwebdriver.driver = iexplorer but still getting the following error. While trying to run in normal selenium Code the IE works fine. Can you guys help me on it.

I mean to run serenity BDD by command line:
```
mvn test verify -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe -Dwebdriver.driver = iexplorer 
```
or 
in your serenity.properties add webdriver.driver = iexplorer  and run tests with 
```
mvn test verify -Dwebdriver.ie.driver=C:\Automation\Resources\IEDriverServer.exe
```

Thanks

**Comment by Kuppusamyi** [comment]
Hi Team,

Any update here?

Thanks & Regards
Iyyappan K.

**Comment by Kuppusamyi** [comment]
Hi Team
Within the project, I have the serenity.properties file.

**Comment by YamStranger** [comment]
Hello @Kuppusamyi 
Sure, please follow advices in last my comment about way of running your tests. 

It seems that this bug appeared not because of serenity but because of some configuration. 
First of all please try to run your tests with firefox (it should be installed in your system and be available in classpath, and it will not require any configuration, only webdriver.driver=firefox ). If you will get no luck in running test in such way - please create simplest project with plain Selenium and try to run some short test with same command line arguments - to make sure that all configured properly, as well as IE versions suitable. 

Looking forward to any updates from you

Thanks!

**Comment by YamStranger** [comment]
It seems that issue was solved and this ticket can be closed. 
Thanks!

**Comment by Kuppusamyi** [comment]
Firefox and Chrome is working fine but IE is not working.

**Comment by YamStranger** [comment]
Did you create simplest project with plain Selenium and tried to run some short test with same command line arguments - to make sure that all configured properly, as well as IE versions suitable? 

If all works with chrome and firerfox but not with IE - it is selenium bug (I think some version conflict)

**Comment by capitolkrs** [comment]
The issue is  because you have set different Protected Modes in Internet Explorer. Read more from this link
https://groups.google.com/forum/#!topic/thucydides-users/ErWTSWFngQI
