### ISSUE TITLE
Problems when using with java 8 and lambdas

### ISSUE THREAD

**Issue by mykolap** [serenity-bdd/serenity-jbehave#87]
If I had lambdas in implementings of the stories - I got next errors:

(java.lang.ArrayIndexOutOfBoundsException: 21568)

java.lang.ArrayIndexOutOfBoundsException: 21568

at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:452)
at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:432)
at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:493)
at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.<init>(BytecodeReadingParanamer.java:338)
at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:101)
at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:90)
at org.jbehave.core.steps.StepCreator.paranamerParameterNames(StepCreator.java:199)
at org.jbehave.core.steps.StepCreator.parameterNames(StepCreator.java:136)
at org.jbehave.core.steps.StepCreator.access$900(StepCreator.java:38)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:644)
at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:596)
at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:340)
at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1072)
at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:938)
at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:977)
at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:887)
at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:811)
at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:784)
at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:416)
at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:387)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
They disappears after fix that I suggest.

**Comment by mykolap** [comment]
https://github.com/mykolap/serenity-jbehave/pull/1/commits/ec1be9412409d470bed164e94bc25345d13deada

**Comment by wakaleo** [comment]
This should be fixed with the next release.

**Comment by wakaleo** [comment]
Fixed in 1.1.33
